INSERT INTO PUBLIC.MENU (DISH_ID, RESTAURANT_ID) VALUES (1, 1);
INSERT INTO PUBLIC.MENU (DISH_ID, RESTAURANT_ID) VALUES (2, 1);
INSERT INTO PUBLIC.MENU (DISH_ID, RESTAURANT_ID) VALUES (36, 2);
INSERT INTO PUBLIC.MENU (DISH_ID, RESTAURANT_ID) VALUES (37, 2);
INSERT INTO PUBLIC.MENU (DISH_ID, RESTAURANT_ID) VALUES (38, 3);
INSERT INTO PUBLIC.MENU (DISH_ID, RESTAURANT_ID) VALUES (39, 3);